name: generate-conda-meta

on:
  release:
    types:
      - "released"

jobs:
  generate-conda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install grayskull
        run: python -m pip install --upgrade grayskull
      - name: Generate conda recipe
        run: python scripts/generate-conda-recipe.py

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes